path="../Examples"

all :	Ex1 Ex2 Ex3 Ex4 Ex5 Ex6 Ex7 Ex8 Ex9 Ex10 Ex11 Ex12 Ex13 Ex14 Ex15 EX16 Ex17

pcode : PCode.c PCode.h
	gcc -c PCode.c

Ex1 :	pcode ${path}/Ex01_pcode.c
	gcc -o Ex1 ${path}/Ex01_pcode.c PCode.o

Ex2 :	pcode ${path}/Ex02_pcode.c
	gcc -o Ex2 ${path}/Ex02_pcode.c PCode.o

Ex3 :	pcode ${path}/Ex03_pcode.c
	gcc -o Ex3 ${path}/Ex3_pcode.c PCode.o

Ex4 :	pcode ${path}/Ex04_pcode.c
	gcc -o Ex4 ${path}/Ex04_pcode.c PCode.o

Ex5 :	pcode ${path}/Ex05_pcode.c
	gcc -o Ex5 ${path}/Ex05_pcode.c PCode.o

Ex6 :	pcode ${path}/Ex06_pcode.c
	gcc -o Ex6 ${path}/Ex06_pcode.c PCode.o

Ex7 :	pcode ${path}/Ex07_pcode.c
	gcc -o Ex7 ${path}/Ex07_pcode.c PCode.o

Ex8 :	pcode ${path}/Ex08_pcode.c
	gcc -o Ex8 ${path}/Ex08_pcode.c PCode.o

Ex9 :	pcode ${path}/Ex09_pcode.c
	gcc -o Ex9 ${path}/Ex09_pcode.c PCode.o

Ex10 :	pcode ${path}/Ex10_pcode.c
	gcc -o Ex10 ${path}/Ex10_pcode.c PCode.o

Ex11 :	pcode ${path}/Ex11_pcode.c
	gcc -o Ex11 ${path}/Ex11_pcode.c PCode.o

Ex12 :	pcode ${path}/Ex12_pcode.c
	gcc -o Ex12 ${path}/Ex12_pcode.c PCode.o

Ex13 :	pcode ${path}/Ex13_pcode.c
	gcc -o Ex13 ${path}/Ex13_pcode.c PCode.o

Ex14 :	pcode ${path}/Ex14_pcode.c
	gcc -o Ex14 ${path}/Ex14_pcode.c PCode.o

Ex15 :	pcode ${path}/Ex15_pcode.c
	gcc -o Ex15 ${path}/Ex15_pcode.c PCode.o

Ex16 :	pcode ${path}/Ex16_pcode.c
	gcc -o Ex16 ${path}/Ex16_pcode.c PCode.o

Ex17 :	pcode ${path}/Ex17_pcode.c
	gcc -o Ex17 ${path}/Ex17_pcode.c PCode.o

clean :
	rm -f *_pcode.c *.o
